# @file
# .travis.yml - Drupal for Travis CI Integration

language: php

sudo: false

php:
  - '7.2'

matrix:

services:
  - mysql

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'
    - DRUPAL_VERSION = '8.8.1'
    - DRUPAL_PATH='/home/travis/build/drupal'
    - PROFILE_PATH='/home/travis/build/drupal/profiles'
    - MODULE_PATH='/home/travis/build/drupal/modules'
    - SIMPLETEST_BASE_URL="http://127.0.0.1:8080"

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_install:
  - composer self-update

install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS drupal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci' -uroot
  - composer global require drush/drush:8.*
  - composer global require PHPUnit/PHPUnit
  - composer global require squizlabs/php_codesniffer:3.*
  - composer global require drupal/coder

before_script:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  # Download drupal.
  - ~/.config/composer/vendor/bin/drush dl drupal-$DRUPAL_VERSION --destination=~/build --drupal-project-rename="drupal"
  # Symlink current build to Drupal test installation.
  - ln -s /home/travis/build/ActiveForAnimals/activeforanimals $PROFILE_PATH
  # Add modules.
  - git clone --branch development https://github.com/EffectiveActivism/effective_activism.git $MODULE_PATH/effective_activism
  - git clone --branch 8.x-1.0-rc1 https://git.drupal.org/project/inline_entity_form.git $MODULE_PATH/inline_entity_form
  - git clone --branch 8.x-1.x https://git.drupal.org/project/imagefield_slideshow.git $MODULE_PATH/imagefield_slideshow
  # Apply patches.
  - cd $MODULE_PATH/inline_entity_form
  - wget -q https://www.drupal.org/files/issues/inline_entity_form-include-access-check-2929727-4_0.patch
  - patch -p1 < inline_entity_form-include-access-check-2929727-4_0.patch
  # Add theme dependencies.
  - cd $DRUPAL_PATH
  # Install drupal.
  - composer require phpunit/phpunit --dev
  - composer require wikimedia/composer-merge-plugin
  - sed -i 's/"installer-paths"/"merge-plugin":: {\n    "include":: [\n      "profiles\/activeforanimals\/themes\/tofu\/composer.json"\n    ],\n    "recurse":: true,\n    "replace":: false,\n    "merge-extra":: false\n  },\n "installer-paths"/g' composer.json
  - cat composer.json
  - composer update
  - ~/.config/composer/vendor/bin/drush --yes site-install activeforanimals --db-url="mysql://$DB_USERNAME@127.0.0.1/$DATABASE" install_configure_form.enable_update_status_module=NULL install_configure_form.enable_update_status_emails=NULL
  - ~/.config/composer/vendor/bin/drush --yes en simpletest
  # Start a webserver in the background and wait for initialization.
  - ~/.config/composer/vendor/bin/drush runserver $SIMPLETEST_BASE_URL &
  - sleep 5
  # Setup phpcs.
  - ~/.config/composer/vendor/bin/phpcs --config-set installed_paths ~/.config/composer/vendor/drupal/coder/coder_sniffer

script:
  - ~/.config/composer/vendor/bin/phpcs --standard=Drupal --runtime-set ignore_warnings_on_exit true --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md $MODULE_PATH/effective_activism/ --ignore=*/vendor/*
  - ~/.config/composer/vendor/bin/phpcs --standard=Drupal --runtime-set ignore_warnings_on_exit true --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md $PROFILE_PATH/activeforanimals/ --ignore=*/vendor/*
  #- ~/.config/composer/vendor/bin/phpcs --standard=DrupalPractice --runtime-set ignore_warnings_on_exit true --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md $MODULE_PATH/effective_activism/ --ignore=*/vendor/*
  #- ~/.config/composer/vendor/bin/phpcs --standard=DrupalPractice --runtime-set ignore_warnings_on_exit true --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md $PROFILE_PATH/activeforanimals/ --ignore=*/vendor/*
  - php core/scripts/run-tests.sh --suppress-deprecations --php $(which php) --color --url $SIMPLETEST_BASE_URL --verbose activeforanimals
