<?php

use Drupal\Core\Link;

/**
 * @file
 * Contains page.page.inc.
 *
 * Page callback for Page page.
 */

/**
 * Prepares variables for Page templates.
 *
 * Default template: page.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the user information and any
 *   - attributes: HTML attributes for the containing element.
 */
function tofu_preprocesxs_page(array &$variables) {
  
}
